sudo: false
language: ruby
rvm:
  - 2.2.1
before_install:
  - git submodule update --init --recursive
before_script:
  - gem install jekyll
  - npm install -g npm
  - npm install -g gulp
  - npm install
  - chmod -R +x ./bin/*
script: ./bin/build.sh
after_script:
  - ./bin/deploy.sh