sudo: required
language: ruby
rvm:
  - 1.9.3
before_script:
  - sudo apt-get install ruby1.9-dev
  - npm install -g npm
  - npm install -g gulp
  - npm install
  - chmod -R +x ./bin/*
script: ./bin/build.sh
after_script:
  - ./bin/deploy.sh