language: ruby
rvm:
  - 1.9.3
before_script:
  - apt-get install ruby-dev
  - npm install -g npm
  - npm install -g gulp
  - npm install
  - chmod -R +x ./bin/*
script: ./bin/build.sh
after_script:
  - ./bin/deploy.sh