markdown: kramdown
permalink: pretty
highlights: false
exclude:
  - bower_components
  - node_modules
  - bower.json
  - gulpfile.js
  - package.json
  - Gemfile
  - Gemfile.lock
  - Readme.md

sass:
  sass_dir: _sass
  style: compressed